main: fatty.arbuckle.minecraft.Main
name: Fatty.Arbuckle
version: 0.1
author: Fatty Arbuckle
description: An test plugin
commands:
  ahoy:
    description: A nautical hello message
    usage: /ahoy
    permission: myplugin.ahoy
    permission-message: You don't have the myplugin.ahoy permission.
  equip:
    description: Turns the block you just left into lava
    usage: /equip [player]
    permission: myplugin.equip
    permission-message: You don't have the myplugin.equip permission.
  arrow:
    description: Sets the arrow type
    usage: /arrow [ normal | flaming | lightning ]
    permission: myplugin.arrow
    permission-message: You don't have the myplugin.arrow permission.
  build:
    description: Builds things
    usage: /build [ wall [ length ] | ??? ]
    permission: myplugin.build
    permission-message: You don't have the myplugin.build permission.
  spawn:
    description: Spawns things near the player
    usage: /spawn player [ thing ]
    permission: myplugin.spawn
    permission-message: You don't have the myplugin.build permission.
  steed:
    description: Summon a horse to ride into battle
    usage: /steed player
    permission: myplugin.steed
    permission-message: You don't have the myplugin.steed permission.
